---
name: "CI"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: go test -race ./...
